
--Regions
INSERT INTO `Region` (`Id`, `name`) VALUES ('1', 'Praha');
INSERT INTO `Region` (`Id`, `name`) VALUES ('2', 'Středočeský kraj');
INSERT INTO `Region` (`Id`, `name`) VALUES ('3', 'Jihočeský kraj');
INSERT INTO `Region` (`Id`, `name`) VALUES ('4', 'Plzeňský kraj');
INSERT INTO `Region` (`Id`, `name`) VALUES ('5', 'Karlovarský kraj');
INSERT INTO `Region` (`Id`, `name`) VALUES ('6', 'Ústecký kraj');
INSERT INTO `Region` (`Id`, `name`) VALUES ('7', 'Liberecký kraj');
INSERT INTO `Region` (`Id`, `name`) VALUES ('8', 'Královéhradecký kraj');
INSERT INTO `Region` (`Id`, `name`) VALUES ('9', 'Pardubický kraj');
INSERT INTO `Region` (`Id`, `name`) VALUES ('10', 'Kraj Vysočina');
INSERT INTO `Region` (`Id`, `name`) VALUES ('11', 'Jihomoravský kraj');
INSERT INTO `Region` (`Id`, `name`) VALUES ('12', 'Olomoucký kraj');
INSERT INTO `Region` (`Id`, `name`) VALUES ('13', 'Moravskoslezský kraj');
INSERT INTO `Region` (`Id`, `name`) VALUES ('14', 'Zlínský kraj');

--Roles
INSERT INTO `Roles` (`Id`, `name`) VALUES ('0', 'User');
INSERT INTO `Roles` (`Id`, `name`) VALUES ('1', 'Dealer');
INSERT INTO `Roles` (`Id`, `name`) VALUES ('2', 'Admin');

--Types
INSERT INTO `Type` (`Id`, `name`) VALUES ('0', 'Byt');
INSERT INTO `Type` (`Id`, `name`) VALUES ('1', 'Dům');
INSERT INTO `Type` (`Id`, `name`) VALUES ('2', 'Chata');
INSERT INTO `Type` (`Id`, `name`) VALUES ('3', 'Pozemek');

/*---------------------------------------------------------*/

--Parametr
INSERT INTO `Parametrs` (`Id`, `name`) VALUES (NULL, 'Konstrukce budovy');
INSERT INTO `Parametrs` (`Id`, `name`) VALUES (NULL, 'Stav budovy');
INSERT INTO `Parametrs` (`Id`, `name`) VALUES (NULL, 'Vlastnictví');
INSERT INTO `Parametrs` (`Id`, `name`) VALUES (NULL, 'Stav bytu');
INSERT INTO `Parametrs` (`Id`, `name`) VALUES (NULL, 'Užitná plocha bytu');

INSERT INTO `Parametrs` (`Id`, `name`) VALUES (NULL, 'Počet podlaží budovy');
INSERT INTO `Parametrs` (`Id`, `name`) VALUES (NULL, 'Podlaží bytu');
INSERT INTO `Parametrs` (`Id`, `name`) VALUES (NULL, 'Vybavení');
INSERT INTO `Parametrs` (`Id`, `name`) VALUES (NULL, 'Lodžie');
INSERT INTO `Parametrs` (`Id`, `name`) VALUES (NULL, 'Připojení k internetu');

/*---------------------------------------------------------*/
/*----------------------- MOCK data ----------------------*/

--Users
INSERT INTO `Users` (`Id`, `IdRole`, `username`, `password`, `name`, `email`, `phone`, `avatar`) 
VALUES (NULL, '2', 'admin', '123456', 'admin', 'admin@gmail.com', '+420 666 777 888', 'user-nicholas-lane-80x80.jpg');

INSERT INTO `Users` (`Id`, `IdRole`, `username`, `password`, `name`, `email`, `phone`, `avatar`) 
VALUES (NULL, '1', 'dealer', '123456', 'Ing. Jarmila Vostrá', 'jarmila@vostra.cz', '+420 666 777 888', 'user-lisa-evans-80x80.jpg');
INSERT INTO `Users` (`Id`, `IdRole`, `username`, `password`, `name`, `email`, `phone`, `avatar`) 
VALUES (NULL, '1', 'dealer2', '123456', 'Jaroslav Kopržral', 'jk@intense.cz', '+420 666 777 888', 'user-ethan-dean-80x80.jpg');

INSERT INTO `Users` (`Id`, `IdRole`, `username`, `password`, `name`, `email`, `phone`, `avatar`) 
VALUES (NULL, '0', 'User1', '123456', 'Pavel Nový', 'pn@gmaill.com', '+420 666 777 888', 'user-nicholas-lane-80x80');


/*Offer - 1*/
INSERT INTO `Offers` (`Id`, `title`, `price`, `thumbnail`, `summary`, `IdType`, `IdRegion`, `IsRent`, `size`, `body`, `address`, `IdDealer`, `IsVisible`) VALUES (NULL, 'AVA Nob Hill', '11500', 'home-img-07-370x250.jpg', 'AVA Nob Hill includes studios and 1 and 2 bedroom apartments that feature an urban-inspired design that extends beyond your walls and throughout the entire community. AVA Nob Hill includes studios and 1 and 2 bedroom apartments that feature an urban-inspired design that extends beyond your walls and throughout the entire community.', '0', '1', b'1', '50', 'Exkluzivně nabízíme prostorný, výborně řešený byt 3+1/L o celkové výměře 81 m2 (včetně lodžie plus sklep), který se nachází ve 4.NP zatepleného zrekonstruovaného domu, v příjemné a klidné lokalitě Praha 9 – Horní Počernice.\r\nByt má zděnou koupelnu s vanou a samostatné WC, vstupní předsíň, dvě ložnice o výměře 12,6 m2 a 12,5 m2, obývací pokoj 22 m2 a kuchyň s jídelnou o výměře 12,4 m2. Na jižně orientovanou lodžii je vstup z obývacího pokoje a je z ní hezký výhled do otevřeného prostoru a na dětské hřiště. Ložnice jsou orientované na severní stranu.\r\nNa podlaze je dlažba, laminátová plovoucí podlaha a koberec, okna jsou plastová se žaluziemi.\r\nByt je vybaven kuchyňskou linkou na míru s vestavěnou elektrickou troubou a sklokeramickou varnou deskou, vestavěnými skříněmi v předsíni a v ložnici. Další vybavení bytu může po dohodě také zůstat.\r\nK bytu náleží sklepní kóje cca 4 m2 a lze využívat kočárkárnu/kolárnu umístěnou v přízemí domu.\r\nMěsíční poplatky jsou pro čtyřčlennou rodinu cca 5 300,- včetně fondu oprav, který je ve výši 1 000,-Kč. Výborně fungující SVJ je pouze jeden vchod domu o jedenácti bytových jednotkách. SVJ není zatíženo žádným úvěrem.\r\nPoloha zrekonstruovaného zatepleného panelového domu je velice výhodná. Přímo u domu je Penny Market a lékárna, v pěším dosahu je pak veškerá občanská vybavenost – MŠ, ZŠ, SOŠ, lékaři, obchody, restaurace, divadlo, několik dětských hřišť a sportovišť. K větším procházkám a sportovnímu vyžití Vás naláká Klánovický les. Stanice metra B – Černý Most je vzdálena jednu cca 1,2 KM od domu a na metro se tak můžete dostat i pěšky nebo pohodlně dojet autobusem za 3 minuty.\r\nNemovitost doporučuji pro pohodlné, klidné rodinné bydlení. Osobní vlastnictví s možností financování hypotékou, kterou Vám rádi pomůžeme vyřídit.', 'Mezilesí, Praha 9 - Prosek', '2', b'1');
INSERT INTO `ParametrsOffers` (`IdOffer`, `IdParametr`, `value`) VALUES ('1', '1', 'panelová'), ('1', '2', 'Stav budovy'), ('1', '3', 'osobní'), ('1', '4', 'po rekonstrukci'), ('1', '5', '41 m2'), ('1', '6', '7 podlaží'), ('1', '7', '3. NP'), ('1', '8', 'částečně zařízený'), ('1', '9', 'ano'), ('1', '10', 'UPC');
INSERT INTO `Request` (`Id`, `IdOffer`, `text`, `name`, `email`, `phone`) VALUES (NULL, '1', 'Dobrý den,\r\nMěl bych zájem o tento dům.', 'Petr Kellner', 'kellner@gmail.com', '+420 666 777 888')
INSERT INTO `Gallery` (`Id`, `IdOffer`, `path`) VALUES (NULL, '1', 'home-img-03-442-280.jpg'), (NULL, '1', 'home-img-01-442-280.jpg'), (NULL, '1', 'home-img-02-442-280.jpg\'), (NULL, '1', 'home-img-04-442-280.jpg'), (NULL, '1', 'home-img-05-370x250.jpg'), (NULL, '1', 'home-img-06-370x250.jpg'), (NULL, '1', 'home-img-07-370x250.jpg');

--Offer
--
INSERT INTO `Offers` (`Id`, `title`, `price`, `thumbnail`, `summary`, `IdType`, `IdRegion`, `IsRent`, `size`, `body`, `address`, `IdDealer`, `IsVisible`) VALUES (NULL, 'SF Flat', '5000000', 'home-img-05-370x250.jpg', 'AVA Nob Hill includes studios and 1 and 2 bedroom apartments that feature an urban-inspired design that extends beyond your walls and throughout the entire community. AVA Nob Hill includes studios and 1 and 2 bedroom apartments that feature an urban-inspired design that extends beyond your walls and throughout the entire community.', '1', '2', b'0', '100', 'Exkluzivně nabízíme prostorný, výborně řešený byt 3+1/L o celkové výměře 81 m2 (včetně lodžie plus sklep), který se nachází ve 4.NP zatepleného zrekonstruovaného domu, v příjemné a klidné lokalitě Praha 9 – Horní Počernice.\r\nByt má zděnou koupelnu s vanou a samostatné WC, vstupní předsíň, dvě ložnice o výměře 12,6 m2 a 12,5 m2, obývací pokoj 22 m2 a kuchyň s jídelnou o výměře 12,4 m2. Na jižně orientovanou lodžii je vstup z obývacího pokoje a je z ní hezký výhled do otevřeného prostoru a na dětské hřiště. Ložnice jsou orientované na severní stranu.\r\nNa podlaze je dlažba, laminátová plovoucí podlaha a koberec, okna jsou plastová se žaluziemi.\r\nByt je vybaven kuchyňskou linkou na míru s vestavěnou elektrickou troubou a sklokeramickou varnou deskou, vestavěnými skříněmi v předsíni a v ložnici. Další vybavení bytu může po dohodě také zůstat.\r\nK bytu náleží sklepní kóje cca 4 m2 a lze využívat kočárkárnu/kolárnu umístěnou v přízemí domu.\r\nMěsíční poplatky jsou pro čtyřčlennou rodinu cca 5 300,- včetně fondu oprav, který je ve výši 1 000,-Kč. Výborně fungující SVJ je pouze jeden vchod domu o jedenácti bytových jednotkách. SVJ není zatíženo žádným úvěrem.\r\nPoloha zrekonstruovaného zatepleného panelového domu je velice výhodná. Přímo u domu je Penny Market a lékárna, v pěším dosahu je pak veškerá občanská vybavenost – MŠ, ZŠ, SOŠ, lékaři, obchody, restaurace, divadlo, několik dětských hřišť a sportovišť. K větším procházkám a sportovnímu vyžití Vás naláká Klánovický les. Stanice metra B – Černý Most je vzdálena jednu cca 1,2 KM od domu a na metro se tak můžete dostat i pěšky nebo pohodlně dojet autobusem za 3 minuty.\r\nNemovitost doporučuji pro pohodlné, klidné rodinné bydlení. Osobní vlastnictví s možností financování hypotékou, kterou Vám rádi pomůžeme vyřídit.', 'Husova, Kladno - Kročehlavy', '3', b'1');
INSERT INTO `Offers` (`Id`, `title`, `price`, `thumbnail`, `summary`, `IdType`, `IdRegion`, `IsRent`, `size`, `body`, `address`, `IdDealer`, `IsVisible`) VALUES (NULL, 'WTO rooms', '11500', 'home-img-06-370x250.jpg', 'AVA Nob Hill includes studios and 1 and 2 bedroom apartments that feature an urban-inspired design that extends beyond your walls and throughout the entire community. AVA Nob Hill includes studios and 1 and 2 bedroom apartments that feature an urban-inspired design that extends beyond your walls and throughout the entire community.', '2', '4', b'1', '35', 'Exkluzivně nabízíme prostorný, výborně řešený byt 3+1/L o celkové výměře 81 m2 (včetně lodžie plus sklep), který se nachází ve 4.NP zatepleného zrekonstruovaného domu, v příjemné a klidné lokalitě Praha 9 – Horní Počernice.\r\nByt má zděnou koupelnu s vanou a samostatné WC, vstupní předsíň, dvě ložnice o výměře 12,6 m2 a 12,5 m2, obývací pokoj 22 m2 a kuchyň s jídelnou o výměře 12,4 m2. Na jižně orientovanou lodžii je vstup z obývacího pokoje a je z ní hezký výhled do otevřeného prostoru a na dětské hřiště. Ložnice jsou orientované na severní stranu.\r\nNa podlaze je dlažba, laminátová plovoucí podlaha a koberec, okna jsou plastová se žaluziemi.\r\nByt je vybaven kuchyňskou linkou na míru s vestavěnou elektrickou troubou a sklokeramickou varnou deskou, vestavěnými skříněmi v předsíni a v ložnici. Další vybavení bytu může po dohodě také zůstat.\r\nK bytu náleží sklepní kóje cca 4 m2 a lze využívat kočárkárnu/kolárnu umístěnou v přízemí domu.\r\nMěsíční poplatky jsou pro čtyřčlennou rodinu cca 5 300,- včetně fondu oprav, který je ve výši 1 000,-Kč. Výborně fungující SVJ je pouze jeden vchod domu o jedenácti bytových jednotkách. SVJ není zatíženo žádným úvěrem.\r\nPoloha zrekonstruovaného zatepleného panelového domu je velice výhodná. Přímo u domu je Penny Market a lékárna, v pěším dosahu je pak veškerá občanská vybavenost – MŠ, ZŠ, SOŠ, lékaři, obchody, restaurace, divadlo, několik dětských hřišť a sportovišť. K větším procházkám a sportovnímu vyžití Vás naláká Klánovický les. Stanice metra B – Černý Most je vzdálena jednu cca 1,2 KM od domu a na metro se tak můžete dostat i pěšky nebo pohodlně dojet autobusem za 3 minuty.\r\nNemovitost doporučuji pro pohodlné, klidné rodinné bydlení. Osobní vlastnictví s možností financování hypotékou, kterou Vám rádi pomůžeme vyřídit.', 'Solní, Plzeň - Jižní Předměstí', '2', b'1');

INSERT INTO `Offers` (`Id`, `title`, `price`, `thumbnail`, `summary`, `IdType`, `IdRegion`, `IsRent`, `size`, `body`, `address`, `IdDealer`, `IsVisible`) VALUES (NULL, 'WTO cabin', '5000', 'home-img-02-442-280.jpg', 'AVA Nob Hill includes studios and 1 and 2 bedroom apartments that feature an urban-inspired design that extends beyond your walls and throughout the entire community. AVA Nob Hill includes studios and 1 and 2 bedroom apartments that feature an urban-inspired design that extends beyond your walls and throughout the entire community.', '2', '4', b'1', '35', 'Exkluzivně nabízíme prostorný, výborně řešený byt 3+1/L o celkové výměře 81 m2 (včetně lodžie plus sklep), který se nachází ve 4.NP zatepleného zrekonstruovaného domu, v příjemné a klidné lokalitě Praha 9 – Horní Počernice.\r\nByt má zděnou koupelnu s vanou a samostatné WC, vstupní předsíň, dvě ložnice o výměře 12,6 m2 a 12,5 m2, obývací pokoj 22 m2 a kuchyň s jídelnou o výměře 12,4 m2. Na jižně orientovanou lodžii je vstup z obývacího pokoje a je z ní hezký výhled do otevřeného prostoru a na dětské hřiště. Ložnice jsou orientované na severní stranu.\r\nNa podlaze je dlažba, laminátová plovoucí podlaha a koberec, okna jsou plastová se žaluziemi.\r\nByt je vybaven kuchyňskou linkou na míru s vestavěnou elektrickou troubou a sklokeramickou varnou deskou, vestavěnými skříněmi v předsíni a v ložnici. Další vybavení bytu může po dohodě také zůstat.\r\nK bytu náleží sklepní kóje cca 4 m2 a lze využívat kočárkárnu/kolárnu umístěnou v přízemí domu.\r\nMěsíční poplatky jsou pro čtyřčlennou rodinu cca 5 300,- včetně fondu oprav, který je ve výši 1 000,-Kč. Výborně fungující SVJ je pouze jeden vchod domu o jedenácti bytových jednotkách. SVJ není zatíženo žádným úvěrem.\r\nPoloha zrekonstruovaného zatepleného panelového domu je velice výhodná. Přímo u domu je Penny Market a lékárna, v pěším dosahu je pak veškerá občanská vybavenost – MŠ, ZŠ, SOŠ, lékaři, obchody, restaurace, divadlo, několik dětských hřišť a sportovišť. K větším procházkám a sportovnímu vyžití Vás naláká Klánovický les. Stanice metra B – Černý Most je vzdálena jednu cca 1,2 KM od domu a na metro se tak můžete dostat i pěšky nebo pohodlně dojet autobusem za 3 minuty.\r\nNemovitost doporučuji pro pohodlné, klidné rodinné bydlení. Osobní vlastnictví s možností financování hypotékou, kterou Vám rádi pomůžeme vyřídit.', 'Solní, Plzeň - Jižní Předměstí', '2', b'1');
INSERT INTO `Offers` (`Id`, `title`, `price`, `thumbnail`, `summary`, `IdType`, `IdRegion`, `IsRent`, `size`, `body`, `address`, `IdDealer`, `IsVisible`) VALUES (NULL, 'SF House', '6000000', 'home-img-03-442-280.jpg', 'AVA Nob Hill includes studios and 1 and 2 bedroom apartments that feature an urban-inspired design that extends beyond your walls and throughout the entire community. AVA Nob Hill includes studios and 1 and 2 bedroom apartments that feature an urban-inspired design that extends beyond your walls and throughout the entire community.', '1', '2', b'0', '250', 'Exkluzivně nabízíme prostorný, výborně řešený byt 3+1/L o celkové výměře 81 m2 (včetně lodžie plus sklep), který se nachází ve 4.NP zatepleného zrekonstruovaného domu, v příjemné a klidné lokalitě Praha 9 – Horní Počernice.\r\nByt má zděnou koupelnu s vanou a samostatné WC, vstupní předsíň, dvě ložnice o výměře 12,6 m2 a 12,5 m2, obývací pokoj 22 m2 a kuchyň s jídelnou o výměře 12,4 m2. Na jižně orientovanou lodžii je vstup z obývacího pokoje a je z ní hezký výhled do otevřeného prostoru a na dětské hřiště. Ložnice jsou orientované na severní stranu.\r\nNa podlaze je dlažba, laminátová plovoucí podlaha a koberec, okna jsou plastová se žaluziemi.\r\nByt je vybaven kuchyňskou linkou na míru s vestavěnou elektrickou troubou a sklokeramickou varnou deskou, vestavěnými skříněmi v předsíni a v ložnici. Další vybavení bytu může po dohodě také zůstat.\r\nK bytu náleží sklepní kóje cca 4 m2 a lze využívat kočárkárnu/kolárnu umístěnou v přízemí domu.\r\nMěsíční poplatky jsou pro čtyřčlennou rodinu cca 5 300,- včetně fondu oprav, který je ve výši 1 000,-Kč. Výborně fungující SVJ je pouze jeden vchod domu o jedenácti bytových jednotkách. SVJ není zatíženo žádným úvěrem.\r\nPoloha zrekonstruovaného zatepleného panelového domu je velice výhodná. Přímo u domu je Penny Market a lékárna, v pěším dosahu je pak veškerá občanská vybavenost – MŠ, ZŠ, SOŠ, lékaři, obchody, restaurace, divadlo, několik dětských hřišť a sportovišť. K větším procházkám a sportovnímu vyžití Vás naláká Klánovický les. Stanice metra B – Černý Most je vzdálena jednu cca 1,2 KM od domu a na metro se tak můžete dostat i pěšky nebo pohodlně dojet autobusem za 3 minuty.\r\nNemovitost doporučuji pro pohodlné, klidné rodinné bydlení. Osobní vlastnictví s možností financování hypotékou, kterou Vám rádi pomůžeme vyřídit.', 'Husova, Kladno - Kročehlavy', '3', b'1');
INSERT INTO `Offers` (`Id`, `title`, `price`, `thumbnail`, `summary`, `IdType`, `IdRegion`, `IsRent`, `size`, `body`, `address`, `IdDealer`, `IsVisible`) VALUES (NULL, 'AVA Office', '8000', 'home-img-04-442-280.jpg', 'AVA Nob Hill includes studios and 1 and 2 bedroom apartments that feature an urban-inspired design that extends beyond your walls and throughout the entire community. AVA Nob Hill includes studios and 1 and 2 bedroom apartments that feature an urban-inspired design that extends beyond your walls and throughout the entire community.', '0', '1', b'1', '45', 'Exkluzivně nabízíme prostorný, výborně řešený byt 3+1/L o celkové výměře 81 m2 (včetně lodžie plus sklep), který se nachází ve 4.NP zatepleného zrekonstruovaného domu, v příjemné a klidné lokalitě Praha 9 – Horní Počernice.\r\nByt má zděnou koupelnu s vanou a samostatné WC, vstupní předsíň, dvě ložnice o výměře 12,6 m2 a 12,5 m2, obývací pokoj 22 m2 a kuchyň s jídelnou o výměře 12,4 m2. Na jižně orientovanou lodžii je vstup z obývacího pokoje a je z ní hezký výhled do otevřeného prostoru a na dětské hřiště. Ložnice jsou orientované na severní stranu.\r\nNa podlaze je dlažba, laminátová plovoucí podlaha a koberec, okna jsou plastová se žaluziemi.\r\nByt je vybaven kuchyňskou linkou na míru s vestavěnou elektrickou troubou a sklokeramickou varnou deskou, vestavěnými skříněmi v předsíni a v ložnici. Další vybavení bytu může po dohodě také zůstat.\r\nK bytu náleží sklepní kóje cca 4 m2 a lze využívat kočárkárnu/kolárnu umístěnou v přízemí domu.\r\nMěsíční poplatky jsou pro čtyřčlennou rodinu cca 5 300,- včetně fondu oprav, který je ve výši 1 000,-Kč. Výborně fungující SVJ je pouze jeden vchod domu o jedenácti bytových jednotkách. SVJ není zatíženo žádným úvěrem.\r\nPoloha zrekonstruovaného zatepleného panelového domu je velice výhodná. Přímo u domu je Penny Market a lékárna, v pěším dosahu je pak veškerá občanská vybavenost – MŠ, ZŠ, SOŠ, lékaři, obchody, restaurace, divadlo, několik dětských hřišť a sportovišť. K větším procházkám a sportovnímu vyžití Vás naláká Klánovický les. Stanice metra B – Černý Most je vzdálena jednu cca 1,2 KM od domu a na metro se tak můžete dostat i pěšky nebo pohodlně dojet autobusem za 3 minuty.\r\nNemovitost doporučuji pro pohodlné, klidné rodinné bydlení. Osobní vlastnictví s možností financování hypotékou, kterou Vám rádi pomůžeme vyřídit.', 'Mezilesí, Praha 9 - Prosek', '2', b'1');
