# Use the official .NET 6.0 SDK image for building the application
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build-env
WORKDIR /App

# Copy the project file and restore dependencies
COPY *.csproj ./
RUN dotnet restore

# Copy the rest of the application code
COPY . ./

# Build and publish the application
RUN dotnet publish -c Release -o out

# Use the official .NET 6.0 runtime image for running the application
FROM mcr.microsoft.com/dotnet/aspnet:6.0
WORKDIR /App

# Copy the published output from the build stage
COPY --from=build-env /App/out .

# Set the entry point for the container
ENTRYPOINT ["dotnet", "Realitky.dll"]

# Expose the port the application runs on
EXPOSE 5216